# NAME = parsing
# CXX = cc
# CXXFLAGS = -fsanitize=address -Wall -Wextra -Werror

# CFILES = cub_parsing.c ft_strcmp.c get_next_line/get_next_line.c \
# 		get_next_line/get_next_line_utils.c struct_element_operation.c  \
# 		file_management.c set_struct_elements.c check_elements.c map_manager.c \
# 		check_map.c check_map_addictional.c set_garbage_struct.c floor_ciel_operation.c\
# 		setup_valid_map.c check_valid_element_addic.c leaks_manager.c

# all : $(NAME)


# $(NAME) : $(CFILES)
# 	make -C libft/ ; $(CXX) $(CXXFLAGS) $(CFILES) libft/libft.a -o $(NAME)

# clean :
# 	rm -rf $(NAME) ; make clean -C ./libft/

# fclean :
# 	rm -rf $(NAME) ; make fclean -C ./libft/

# re : fclean all

# .PHONY : all clean fclean re